WaterPumpRelayGpio: 6
DatabaseLocation: "./WaterPumpDatabase"
ApiKey: "c6CkJuE4FMiD7osPCuLnMABcYTqTdIWlqRG6Sdow7wtpBJyRRGjFxYqgisbk5pKWM4OaoKZjCwKn3UZ6uriPf9wLIdg0q4yGlXGgUVTR5OK0vWMykJ1sb5j2dL9thGFo"